spring:
  application:
    name: learn-kstream-73
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    streams:
      application-id: learn-kstream-73
      bootstrap-servers: localhost:9092
    properties:
      default:
        deserialization:
          exception:
            handler: com.ipa.learnkstream73.exceptionhandler.CustomStreamsDeserializationExceptionHandler
            #org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
        production:
          exception:
            handler:  com.ipa.learnkstream73.exceptionhandler.CustomStreamsProductionExceptionHandler